### ISSUE TITLE
`getConfirmedFormula` and `getNonRejectedFormula` not exported

### ISSUE THREAD

**Issue by MarcoNiemann** [mbq/Boruta#1] opened 2016-11-20 14:24 UTC
I have quickly read through the change logs of the last versions, but I was unable to find any specific reason why the two methods `getConfirmedFormula` and `getNonRejectedFormula` are not exported any longer.

Since they are apparently useful for a set of purposes (e.g. *to build models based on the derived formulae*), I suggest that they might be added again in future versions.

**Comment by mbq** [comment] 2016-11-21 16:07
The problem is that returning formula is not always possible (for instance when Boruta was called with (x,y) interface, which is BTW encouraged due to superior performance). Re-implementation is obviously possible, but I doubt it is worth the effort of handling all the subtle cases.

**Comment by MarcoNiemann** [comment] 2016-11-21 19:10
I am not 100% sure what you suggest by the `(x,y)` interface?

Are you referring to the different options to call the `Boruta` function? Like I did it in the following two versions now:
```r
# This was the version I tried first.
Boruta({targetVariable} ~ ., data = {dataSet}, ntree = 500, doTrace = 2, maxRuns = 1000)

# This is the version I tried second.
Boruta(x = {dataSetExclTargetVariable}, y = {targetVariable}, ntree = 500, doTrace = 2, maxRuns = 1000)
```

While I experienced some speed-up by the later invocation, overall I would say that the difference is marginal. But that might be because I still do something wrong there.

With regard to the initial question I understand your reasoning. I was only surprised since I actually tried the package based on the jstat-paper describing it and then figured out that some functions were not working anymore (*without any notice in the change log*). But if that is due to reimplementatation of some parts of the package that is ok. Would only be cool if you might add such changes to the update notices (*would make it easier to follow them*) [just as a suggestion].

**Comment by mbq** [comment] 2016-11-22 01:12
Yup; the difference becomes significant with larger data, since formula causes redundant copying. 

You're certainly right about the NEWS file, I'll update it with the next release. Formula getters have landed on my reconsider list.

**Comment by mbq** [comment] 2017-01-26 15:13
Fixed in https://github.com/mbq/Boruta/commit/630278285cc7ee057476e72e9a54fb0f56fc0bdd; formula getters are back.

Boruta 5.2 containing the fix should appear on CRAN soon.

**Closed as completed by mbq** 2017-01-26 15:13 UTC
